### PR TITLE
Stuff before launch

### PR DESCRIPTION
**Pull request by jkchuynh829**

### CODE REVIEW

**Comment by canoc62** [comment]
Looks good! I pushed up a change to wrap the last of the questions that weren't wrapped with the Question component. Dorothy is thinking of some updates for some of the FAQs questions. And I still gotta plan the registry portion!

**Comment by canoc62** [comment]
Dorothy's notes: 
Wedding Party page: 2 columns, each section will mirror each other meaning Maid of Honor...........Best Man

1st column
Maid of Honor
Felicia Le

Bridesmaids
Cynthia Le
Tiffany Le
Chelsea Cano

Bride's Parents
Frank Le
Tina Dao

Flower Boys
Spanky
Hunter

2nd column
Best Man
Zach Cuarto

Groomsmen
Jimmy Huynh
Jimmy Tran
Kevin Bendo
Nick Cuarto
Ranny Lowe
Robert Macaisa
Robert Siegel
Theodore Roque

Groom's Parents
Nilo Cano
Edita Cano

Ring Bearer
Chucky
Corky

**Comment by canoc62** [comment]
Dorothy's notes part 2:

1. can we make the width of the text on the FAQs page bigger? like it will visually spread from beginning of RSVP to end of THINGS TO DO in the nav bar.
2. the bar on the THINGS TO DO page is still pink, are you still planning to make it gold or something? I don't remember what you were gonna do here.

REGISTRY page - CHRIS WILL WORK ON THIS CONTENT
put at top, similar to things to do page: We do not have a registry open and prefer cash gifts! You can send us a cash gift via Venmo, Zelle or PayPal or write a check out to either of us and drop it in our gift box at the reception.

**Comment by jkchuynh829** [comment]
> Best Man Zach Cuarto
> 
> Groomsmen Jimmy Huynh Jimmy Tran Kevin Bendo Nick Cuarto Ranny Lowe Robert Macaisa Robert Siegel Theodore Roque
> 
> Groom's Parents Nilo Cano Edita Cano
> 
> Ring Bearer Chucky Corky

WILL DO ALL THE THINGS :)

**Pull request merged**
